apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  template:
    spec:
      containers:
      - name: my-nginx
        env:
          - name: HELLO
            value: galaxy
          - name: WHATS
            value: up doc
