apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        env:
          - name: HELLO
            value: galaxy
          - name: WHATS
            value: this
